name: C++ CI

on:
  push:
    branches:
      - main
      - callable_concepts
  pull_request:
    branches:
      - main
      - callable_concepts

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCALLABLE_TRAITS_BUILD_TESTS=ON

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

    - name: Expect compile failure for invalid concepts
      run: |
        mkdir -p build/invalid_test
        cd build/invalid_test
        set +e
        cmake ../../../test/invalid_test
        cmake --build . && echo "❌ invalid_concepts_test compiled successfully — this is an error!" && exit 1
        echo "✅ invalid_concepts_test failed to compile as expected."
