name: C++ CI

on:
  push:
    branches:
      - main
      - callable_concepts
      - package
      - enhanced-tests
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - name: GCC 12
            compiler: gcc-12
            compiler_cxx: g++-12
          - name: GCC 13
            compiler: gcc-13
            compiler_cxx: g++-13
          - name: GCC 14
            compiler: gcc-14
            compiler_cxx: g++-14

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        if [ "${{ matrix.compiler }}" = "gcc-14" ]; then
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
        fi
        sudo apt-get install -y cmake ninja-build ${{ matrix.compiler }} ${{ matrix.compiler_cxx }}

    - name: Configure and build library
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler_cxx }} \
          -DCMAKE_CXX_STANDARD=23
        cmake --build build
        sudo cmake --install build

    - name: Configure and build tests
      run: |
        cmake -B build_test -G Ninja -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler_cxx }} \
          -DCMAKE_CXX_STANDARD=23 \
          -DCALLABLE_TRAITS_BUILD_TESTS=ON
        cmake --build build_test

    - name: Run tests
      run: ctest --test-dir build_test --output-on-failure

    - name: Expect compile failure for invalid concepts
      run: |
        mkdir -p build_test/invalid_test
        cd build_test/invalid_test
        set +e
        cmake ../../test/invalid_test \
          -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler_cxx }} \
          -DCMAKE_CXX_STANDARD=23
        cmake --build . && echo "❌ invalid_concepts_test compiled successfully — this is an error!" && exit 1
        echo "✅ invalid_concepts_test failed to compile as expected."
